name: Generate Snake Animation 🐍

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk@master
        with:
          github_user_name: Ricky-Hacker001
          outputs: |
            ./github-contribution-grid-snake.svg

      - name: Move file to output folder
        run: |
          mkdir -p output
          mv github-contribution-grid-snake.svg output/

      - name: Commit and push generated SVG
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "🐍 Update GitHub contribution snake"
          add: "output/github-contribution-grid-snake.svg"
